server:
  port: 8888

spring:
  application:
    name: file-sharing
  servlet:
    multipart:
      file-size-threshold: 0 # 将文件写入磁盘的阀值 值可以使用后缀“MB ”或“ KB 来表示兆字节或字节大小
      max-file-size: 4096MB #单个文件进最大值
      max-request-size: 4096MB #所有文件最大值

app:
  version: 1.0.0
  file:
    dir: D:/root/file-sharing
  password:
    offset: 2