server:
  port: 8088
  servlet:
    session:
      timeout: 3h

spring:
  application:
    name: file-sharing
  servlet:
    multipart:
      file-size-threshold: 0 # 将文件写入磁盘的阀值 值可以使用后缀“MB ”或“ KB 来表示兆字节或字节大小
      max-file-size: 2048MB # 上传单个文件最大值
      max-request-size: 2048MB # 上传所有文件最大值

app:
  version: 1.0.0
  file:
    dir: /root/myapp/file-sharing/files # 文件存储路径
    max-number: 10 # 文件最大数量
    max-total-size: 5000000000 # 所有文件最大容量 5G
  password:
    offset: 2 # 密码偏移
    long-term: sunnyangeya # 长期密码